// Copies the web app (../index.html at the repo root) into a TypeScript module
// so it is compiled into the app bundle and opens with no network connection.
// Runs on `npm install` and every time Metro starts (see metro.config.js).
const fs = require('fs');
const path = require('path');

const source = path.resolve(__dirname, '..', '..', 'index.html');
const target = path.resolve(__dirname, '..', 'src', 'webAppHtml.generated.ts');

function embedWebApp() {
  const html = fs.readFileSync(source, 'utf8');
  const build = (html.match(/<meta name="fttech-build" content="([^"]+)"/) || [])[1] || 'unknown';
  const contents =
    '// Generated by scripts/embed-web-app.js from ../index.html. Do not edit.\n' +
    `export const WEB_APP_BUILD = ${JSON.stringify(build)};\n` +
    `export const WEB_APP_HTML = ${JSON.stringify(html)};\n`;
  const existing = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : null;
  if (existing !== contents) fs.writeFileSync(target, contents);
  return build;
}

module.exports = { embedWebApp };

if (require.main === module) {
  console.log(`Embedded FTTechApp web build ${embedWebApp()}`);
}
